name: Export Pull Requests Timestamps

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  export-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Export Pull Requests to CSV
        run: |
          python scripts/export_pull_requests.py

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pull-requests-timestamps
          path: pull_requests.csv
